# -*- coding: utf-8 -*-
"""004promedio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_gl8a-VyPQmGFSRySAuK3sHYs5vzms3
"""

# Este programa te ayudara a calcular tu promedio final del curso

print('Este programa calcula el promedio de nota de un alumno:\n')
nombre = input('Escribe tu nombre: ')
parcial1 = float(input('Escribe tu nota del parcial 1: '))
parcial2 = float(input('Escribe tu nota del parcial 2: '))
final = float(input('Escribe tu nota del final: '))

prom = (parcial1 + parcial2 + final)/3
print(f'{nombre}, tu promedio es: ', round(prom,2))